# Generated by Django 3.0.8 on 2020-12-22 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20201222_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
