# Generated by Django 3.0.8 on 2020-12-16 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pant',
            old_name='pant_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='shirt',
            old_name='shirt_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='shoe',
            old_name='shoe_image',
            new_name='image',
        ),
    ]
